"""initial_schema

Revision ID: 2e6ad7447506
Revises: 
Create Date: 2026-07-26 10:52:35.083007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6ad7447506'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_key', sa.String(length=100), nullable=True),
    sa.Column('type_name', sa.String(length=100), nullable=True),
    sa.Column('parent_type_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_types_type_key'), ['type_key'], unique=True)

    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('model_quality', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_metric_key'), ['metric_key'], unique=True)

    op.create_table('body_battery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('body_battery_charged', sa.Float(), nullable=True),
    sa.Column('body_battery_drained', sa.Float(), nullable=True),
    sa.Column('body_battery_charged_start', sa.Float(), nullable=True),
    sa.Column('body_battery_drained_start', sa.Float(), nullable=True),
    sa.Column('max_body_battery', sa.Float(), nullable=True),
    sa.Column('min_body_battery', sa.Float(), nullable=True),
    sa.Column('net_charge', sa.Float(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_battery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_battery_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_battery_id'), ['id'], unique=False)

    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('total_descent', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('activity_types_breakdown', sa.JSON(), nullable=True),
    sa.Column('best_distance', sa.Float(), nullable=True),
    sa.Column('best_duration', sa.Float(), nullable=True),
    sa.Column('best_pace', sa.Float(), nullable=True),
    sa.Column('best_speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_summaries_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_daily_summaries_id'), ['id'], unique=False)

    op.create_table('garmin_performance_metrics',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('vo2_max_precise', sa.Float(), nullable=True),
    sa.Column('fitness_age', sa.Float(), nullable=True),
    sa.Column('max_met_category', sa.Integer(), nullable=True),
    sa.Column('altitude_acclimation', sa.Float(), nullable=True),
    sa.Column('previous_altitude_acclimation', sa.Float(), nullable=True),
    sa.Column('heat_acclimation_percentage', sa.Float(), nullable=True),
    sa.Column('previous_heat_acclimation_percentage', sa.Float(), nullable=True),
    sa.Column('current_altitude', sa.Float(), nullable=True),
    sa.Column('heat_trend', sa.String(length=100), nullable=True),
    sa.Column('altitude_trend', sa.String(length=100), nullable=True),
    sa.Column('monthly_load_aerobic_low', sa.Float(), nullable=True),
    sa.Column('monthly_load_aerobic_high', sa.Float(), nullable=True),
    sa.Column('monthly_load_anaerobic', sa.Float(), nullable=True),
    sa.Column('monthly_load_aerobic_low_target_min', sa.Float(), nullable=True),
    sa.Column('monthly_load_aerobic_low_target_max', sa.Float(), nullable=True),
    sa.Column('monthly_load_aerobic_high_target_min', sa.Float(), nullable=True),
    sa.Column('monthly_load_aerobic_high_target_max', sa.Float(), nullable=True),
    sa.Column('monthly_load_anaerobic_target_min', sa.Float(), nullable=True),
    sa.Column('monthly_load_anaerobic_target_max', sa.Float(), nullable=True),
    sa.Column('training_balance_feedback_phrase', sa.String(length=100), nullable=True),
    sa.Column('training_status', sa.Integer(), nullable=True),
    sa.Column('training_status_feedback_phrase', sa.String(length=255), nullable=True),
    sa.Column('sport', sa.String(length=100), nullable=True),
    sa.Column('sub_sport', sa.String(length=100), nullable=True),
    sa.Column('fitness_trend', sa.Integer(), nullable=True),
    sa.Column('fitness_trend_sport', sa.String(length=100), nullable=True),
    sa.Column('acwr_percent', sa.Float(), nullable=True),
    sa.Column('acwr_status', sa.String(length=100), nullable=True),
    sa.Column('acwr_status_feedback', sa.String(length=255), nullable=True),
    sa.Column('daily_training_load_acute', sa.Float(), nullable=True),
    sa.Column('daily_training_load_chronic', sa.Float(), nullable=True),
    sa.Column('daily_acute_chronic_workload_ratio', sa.Float(), nullable=True),
    sa.Column('load_tunnel_min', sa.Float(), nullable=True),
    sa.Column('load_tunnel_max', sa.Float(), nullable=True),
    sa.Column('endurance_score', sa.Float(), nullable=True),
    sa.Column('endurance_classification', sa.Integer(), nullable=True),
    sa.Column('hill_score', sa.Float(), nullable=True),
    sa.Column('hill_endurance_score', sa.Float(), nullable=True),
    sa.Column('hill_strength_score', sa.Float(), nullable=True),
    sa.Column('raw_maxmet', sa.JSON(), nullable=True),
    sa.Column('raw_training_load_balance', sa.JSON(), nullable=True),
    sa.Column('raw_training_status', sa.JSON(), nullable=True),
    sa.Column('raw_endurance_score', sa.JSON(), nullable=True),
    sa.Column('raw_hill_score', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('garmin_performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garmin_performance_metrics_date'), ['date'], unique=False)

    op.create_table('health_data_missing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('missing_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_type', 'missing_date', name='uq_health_data_missing_type_date')
    )
    with op.batch_alter_table('health_data_missing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_data_missing_data_type'), ['data_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_data_missing_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_data_missing_missing_date'), ['missing_date'], unique=False)

    op.create_table('hrv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('measurement_time', sa.DateTime(), nullable=True),
    sa.Column('rmssd', sa.Float(), nullable=True),
    sa.Column('pnn50', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('baseline_balanced_lower', sa.Float(), nullable=True),
    sa.Column('baseline_balanced_upper', sa.Float(), nullable=True),
    sa.Column('baseline_low_upper', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('measurement_type', sa.String(length=50), nullable=True),
    sa.Column('activity_id', sa.String(length=255), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('breathing_rate', sa.Float(), nullable=True),
    sa.Column('measurement_quality', sa.String(length=20), nullable=True),
    sa.Column('measurement_duration', sa.Float(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hrv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hrv_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hrv_measurement_date'), ['measurement_date'], unique=False)

    op.create_table('lactate_threshold_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('sync_context', sa.String(length=50), nullable=True),
    sa.Column('lactate_threshold_speed', sa.Float(), nullable=True),
    sa.Column('lactate_threshold_heart_rate', sa.Float(), nullable=True),
    sa.Column('raw_lactate_threshold_speed', sa.Float(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lactate_threshold_history', schema=None) as batch_op:
        batch_op.create_index('idx_lactate_threshold_history_observed_at', ['observed_at'], unique=False)
        batch_op.create_index('idx_lactate_threshold_history_source_observed_at', ['source', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lactate_threshold_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lactate_threshold_history_observed_at'), ['observed_at'], unique=False)

    op.create_table('monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('month_start_date', sa.Date(), nullable=True),
    sa.Column('month_end_date', sa.Date(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_tss', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('total_descent', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('activities_per_day', sa.Float(), nullable=True),
    sa.Column('distance_per_day', sa.Float(), nullable=True),
    sa.Column('duration_per_day', sa.Float(), nullable=True),
    sa.Column('activities_per_week', sa.Float(), nullable=True),
    sa.Column('distance_per_week', sa.Float(), nullable=True),
    sa.Column('duration_per_week', sa.Float(), nullable=True),
    sa.Column('activity_types_breakdown', sa.JSON(), nullable=True),
    sa.Column('best_distance', sa.Float(), nullable=True),
    sa.Column('best_duration', sa.Float(), nullable=True),
    sa.Column('best_pace', sa.Float(), nullable=True),
    sa.Column('best_speed', sa.Float(), nullable=True),
    sa.Column('distance_trend', sa.Float(), nullable=True),
    sa.Column('duration_trend', sa.Float(), nullable=True),
    sa.Column('activities_trend', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_summaries_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_summaries_year'), ['year'], unique=False)

    op.create_table('resting_heart_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('measurement_method', sa.String(length=50), nullable=True),
    sa.Column('measurement_time', sa.DateTime(), nullable=True),
    sa.Column('measurement_quality', sa.String(length=20), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resting_heart_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resting_heart_rate_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resting_heart_rate_measurement_date'), ['measurement_date'], unique=True)

    op.create_table('sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_date', sa.Date(), nullable=True),
    sa.Column('bedtime', sa.DateTime(), nullable=True),
    sa.Column('wake_time', sa.DateTime(), nullable=True),
    sa.Column('total_sleep_time', sa.Float(), nullable=True),
    sa.Column('deep_sleep_time', sa.Float(), nullable=True),
    sa.Column('light_sleep_time', sa.Float(), nullable=True),
    sa.Column('rem_sleep_time', sa.Float(), nullable=True),
    sa.Column('awake_time', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.String(length=20), nullable=True),
    sa.Column('deep_sleep_percent', sa.Float(), nullable=True),
    sa.Column('light_sleep_percent', sa.Float(), nullable=True),
    sa.Column('rem_sleep_percent', sa.Float(), nullable=True),
    sa.Column('awake_percent', sa.Float(), nullable=True),
    sa.Column('sleep_efficiency', sa.Float(), nullable=True),
    sa.Column('sleep_latency', sa.Float(), nullable=True),
    sa.Column('wake_episodes', sa.Integer(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('lowest_heart_rate', sa.Float(), nullable=True),
    sa.Column('highest_heart_rate', sa.Float(), nullable=True),
    sa.Column('heart_rate_variability', sa.Float(), nullable=True),
    sa.Column('average_spo2', sa.Float(), nullable=True),
    sa.Column('lowest_spo2', sa.Float(), nullable=True),
    sa.Column('average_respiration_rate', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('movement_score', sa.Float(), nullable=True),
    sa.Column('restless_moments', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('detailed_sleep_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_sleep_date'), ['sleep_date'], unique=True)

    op.create_table('sleep_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('heart_rate_variability', sa.Float(), nullable=True),
    sa.Column('respiration_rate', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('movement_intensity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_stages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_stages_sleep_date'), ['sleep_date'], unique=False)

    op.create_table('stress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stress_date', sa.Date(), nullable=True),
    sa.Column('stress_level', sa.Float(), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('stress_time', sa.Float(), nullable=True),
    sa.Column('rest_time', sa.Float(), nullable=True),
    sa.Column('low_stress_time', sa.Float(), nullable=True),
    sa.Column('medium_stress_time', sa.Float(), nullable=True),
    sa.Column('high_stress_time', sa.Float(), nullable=True),
    sa.Column('activity_stress_duration', sa.Float(), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('detailed_stress_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stress_stress_date'), ['stress_date'], unique=True)

    op.create_table('sync_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_status'), ['status'], unique=False)

    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('last_synced_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_state_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_state_key'), ['key'], unique=True)

    op.create_table('weekly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_end_date', sa.Date(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('total_descent', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('activities_per_day', sa.Float(), nullable=True),
    sa.Column('distance_per_day', sa.Float(), nullable=True),
    sa.Column('duration_per_day', sa.Float(), nullable=True),
    sa.Column('activity_types_breakdown', sa.JSON(), nullable=True),
    sa.Column('best_distance', sa.Float(), nullable=True),
    sa.Column('best_duration', sa.Float(), nullable=True),
    sa.Column('best_pace', sa.Float(), nullable=True),
    sa.Column('best_speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('weekly_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_summaries_week_number'), ['week_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_summaries_year'), ['year'], unique=False)

    op.create_table('weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=True),
    sa.Column('measurement_time', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.Column('bone_mass', sa.Float(), nullable=True),
    sa.Column('body_water_percent', sa.Float(), nullable=True),
    sa.Column('visceral_fat', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('measurement_method', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_measurement_date'), ['measurement_date'], unique=False)

    op.create_table('yearly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('total_descent', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('activities_per_day', sa.Float(), nullable=True),
    sa.Column('distance_per_day', sa.Float(), nullable=True),
    sa.Column('duration_per_day', sa.Float(), nullable=True),
    sa.Column('activities_per_week', sa.Float(), nullable=True),
    sa.Column('distance_per_week', sa.Float(), nullable=True),
    sa.Column('duration_per_week', sa.Float(), nullable=True),
    sa.Column('activities_per_month', sa.Float(), nullable=True),
    sa.Column('distance_per_month', sa.Float(), nullable=True),
    sa.Column('duration_per_month', sa.Float(), nullable=True),
    sa.Column('activity_types_breakdown', sa.JSON(), nullable=True),
    sa.Column('monthly_breakdown', sa.JSON(), nullable=True),
    sa.Column('best_distance', sa.Float(), nullable=True),
    sa.Column('best_duration', sa.Float(), nullable=True),
    sa.Column('best_pace', sa.Float(), nullable=True),
    sa.Column('best_speed', sa.Float(), nullable=True),
    sa.Column('distance_trend', sa.Float(), nullable=True),
    sa.Column('duration_trend', sa.Float(), nullable=True),
    sa.Column('activities_trend', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yearly_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yearly_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yearly_summaries_year'), ['year'], unique=True)

    op.create_table('activities',
    sa.Column('activity_id', sa.String(length=255), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('moving_duration', sa.Float(), nullable=True),
    sa.Column('elapsed_duration', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('average_moving_speed', sa.Float(), nullable=True),
    sa.Column('avg_grade_adjusted_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('average_pace', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('min_heart_rate', sa.Float(), nullable=True),
    sa.Column('average_running_cadence', sa.Float(), nullable=True),
    sa.Column('max_running_cadence', sa.Float(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('ground_contact_time', sa.Float(), nullable=True),
    sa.Column('stride_length', sa.Float(), nullable=True),
    sa.Column('vertical_oscillation', sa.Float(), nullable=True),
    sa.Column('vertical_ratio', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('total_descent', sa.Float(), nullable=True),
    sa.Column('min_elevation', sa.Float(), nullable=True),
    sa.Column('max_elevation', sa.Float(), nullable=True),
    sa.Column('average_power', sa.Float(), nullable=True),
    sa.Column('max_power', sa.Float(), nullable=True),
    sa.Column('normalized_power', sa.Float(), nullable=True),
    sa.Column('training_stress_score', sa.Float(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('total_training_effect', sa.Float(), nullable=True),
    sa.Column('total_anaerobic_training_effect', sa.Float(), nullable=True),
    sa.Column('training_effect_label', sa.String(length=100), nullable=True),
    sa.Column('aerobic_training_effect_message', sa.String(length=255), nullable=True),
    sa.Column('anaerobic_training_effect_message', sa.String(length=255), nullable=True),
    sa.Column('epoc', sa.Float(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('vo2_max_precise', sa.Float(), nullable=True),
    sa.Column('lactate_threshold_heart_rate', sa.Float(), nullable=True),
    sa.Column('lactate_threshold_speed', sa.Float(), nullable=True),
    sa.Column('recovery_time', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('negative_split_percent', sa.Float(), nullable=True),
    sa.Column('running_economy', sa.Float(), nullable=True),
    sa.Column('decoupling_percent', sa.Float(), nullable=True),
    sa.Column('avg_efficiency_factor', sa.Float(), nullable=True),
    sa.Column('median_efficiency_factor', sa.Float(), nullable=True),
    sa.Column('steady_state_efficiency_factor', sa.Float(), nullable=True),
    sa.Column('efficiency_data_quality', sa.Float(), nullable=True),
    sa.Column('decoupling_suitability_flag', sa.String(length=50), nullable=True),
    sa.Column('decoupling_reason_if_unsuitable', sa.String(length=255), nullable=True),
    sa.Column('decoupling_data_quality_score', sa.Float(), nullable=True),
    sa.Column('fatigue_resistance_score', sa.Float(), nullable=True),
    sa.Column('pace_drop_pct', sa.Float(), nullable=True),
    sa.Column('hr_drift_pct', sa.Float(), nullable=True),
    sa.Column('cadence_drop_pct', sa.Float(), nullable=True),
    sa.Column('ef_drop_pct', sa.Float(), nullable=True),
    sa.Column('training_readiness_score', sa.Float(), nullable=True),
    sa.Column('body_battery_start', sa.Float(), nullable=True),
    sa.Column('begin_potential_stamina', sa.Float(), nullable=True),
    sa.Column('end_potential_stamina', sa.Float(), nullable=True),
    sa.Column('min_available_stamina', sa.Float(), nullable=True),
    sa.Column('activity_body_battery_delta', sa.Float(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('has_detailed_data', sa.Boolean(), nullable=True),
    sa.Column('detailed_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('idx_activity_type_start_time', ['activity_type_id', 'start_time'], unique=False)
        batch_op.create_index('idx_distance_duration', ['distance', 'duration', 'start_time'], unique=False)
        batch_op.create_index('idx_duration_distance', ['duration', 'distance'], unique=False)
        batch_op.create_index('idx_epoc_tss', ['epoc', 'training_stress_score'], unique=False)
        batch_op.create_index('idx_power_null', ['average_power'], unique=False)
        batch_op.create_index('idx_start_time_activity_type', ['start_time', 'activity_type_id'], unique=False)
        batch_op.create_index('idx_start_time_desc', ['start_time'], unique=False)
        batch_op.create_index('idx_start_time_range', ['start_time', 'end_time'], unique=False)
        batch_op.create_index('idx_tss_null', ['training_stress_score'], unique=False)
        batch_op.create_index('idx_vo2max', ['vo2_max'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_distance'), ['distance'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_start_time'), ['start_time'], unique=False)

    op.create_table('activity_laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=255), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('max_cadence', sa.Float(), nullable=True),
    sa.Column('total_ascent', sa.Float(), nullable=True),
    sa.Column('total_descent', sa.Float(), nullable=True),
    sa.Column('average_power', sa.Float(), nullable=True),
    sa.Column('max_power', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_laps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_laps_id'), ['id'], unique=False)

    op.create_table('activity_route_fingerprints',
    sa.Column('activity_id', sa.String(length=255), nullable=False),
    sa.Column('route_group_key', sa.String(length=100), nullable=True),
    sa.Column('route_hash', sa.String(length=64), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=True),
    sa.Column('gps_point_count', sa.Integer(), nullable=True),
    sa.Column('sampled_point_count', sa.Integer(), nullable=True),
    sa.Column('route_distance_m', sa.Float(), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('centroid_latitude', sa.Float(), nullable=True),
    sa.Column('centroid_longitude', sa.Float(), nullable=True),
    sa.Column('bbox_min_latitude', sa.Float(), nullable=True),
    sa.Column('bbox_min_longitude', sa.Float(), nullable=True),
    sa.Column('bbox_max_latitude', sa.Float(), nullable=True),
    sa.Column('bbox_max_longitude', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sampled_points', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('method_version', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    with op.batch_alter_table('activity_route_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_route_fingerprints_route_group_key'), ['route_group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_route_fingerprints_route_hash'), ['route_hash'], unique=False)

    op.create_table('activity_route_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=255), nullable=False),
    sa.Column('matched_activity_id', sa.String(length=255), nullable=False),
    sa.Column('same_route', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('reverse_direction', sa.Boolean(), nullable=False),
    sa.Column('mean_distance_m', sa.Float(), nullable=True),
    sa.Column('p90_distance_m', sa.Float(), nullable=True),
    sa.Column('start_distance_m', sa.Float(), nullable=True),
    sa.Column('end_distance_m', sa.Float(), nullable=True),
    sa.Column('distance_ratio', sa.Float(), nullable=True),
    sa.Column('overlap_quality', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('method_version', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['matched_activity_id'], ['activities.activity_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'matched_activity_id', name='uq_activity_route_match_pair')
    )
    with op.batch_alter_table('activity_route_matches', schema=None) as batch_op:
        batch_op.create_index('idx_route_match_activity_score', ['activity_id', 'similarity_score'], unique=False)
        batch_op.create_index('idx_route_match_same_route', ['same_route', 'similarity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_route_matches_id'), ['id'], unique=False)

    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('activity_id', sa.String(length=255), nullable=True),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_record_type'), ['record_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_personal_records_id'))

    op.drop_table('personal_records')
    with op.batch_alter_table('activity_route_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_route_matches_id'))
        batch_op.drop_index('idx_route_match_same_route')
        batch_op.drop_index('idx_route_match_activity_score')

    op.drop_table('activity_route_matches')
    with op.batch_alter_table('activity_route_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_route_fingerprints_route_hash'))
        batch_op.drop_index(batch_op.f('ix_activity_route_fingerprints_route_group_key'))

    op.drop_table('activity_route_fingerprints')
    with op.batch_alter_table('activity_laps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_laps_id'))

    op.drop_table('activity_laps')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_start_time'))
        batch_op.drop_index(batch_op.f('ix_activities_duration'))
        batch_op.drop_index(batch_op.f('ix_activities_distance'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_id'))
        batch_op.drop_index('idx_vo2max')
        batch_op.drop_index('idx_tss_null')
        batch_op.drop_index('idx_start_time_range')
        batch_op.drop_index('idx_start_time_desc')
        batch_op.drop_index('idx_start_time_activity_type')
        batch_op.drop_index('idx_power_null')
        batch_op.drop_index('idx_epoc_tss')
        batch_op.drop_index('idx_duration_distance')
        batch_op.drop_index('idx_distance_duration')
        batch_op.drop_index('idx_activity_type_start_time')

    op.drop_table('activities')
    with op.batch_alter_table('yearly_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yearly_summaries_year'))
        batch_op.drop_index(batch_op.f('ix_yearly_summaries_id'))

    op.drop_table('yearly_summaries')
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_measurement_date'))
        batch_op.drop_index(batch_op.f('ix_weight_id'))

    op.drop_table('weight')
    with op.batch_alter_table('weekly_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_summaries_year'))
        batch_op.drop_index(batch_op.f('ix_weekly_summaries_week_number'))
        batch_op.drop_index(batch_op.f('ix_weekly_summaries_id'))

    op.drop_table('weekly_summaries')
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_state_key'))
        batch_op.drop_index(batch_op.f('ix_sync_state_id'))

    op.drop_table('sync_state')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_job_id'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('stress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_stress_date'))
        batch_op.drop_index(batch_op.f('ix_stress_id'))

    op.drop_table('stress')
    with op.batch_alter_table('sleep_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_stages_sleep_date'))
        batch_op.drop_index(batch_op.f('ix_sleep_stages_id'))

    op.drop_table('sleep_stages')
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_sleep_date'))
        batch_op.drop_index(batch_op.f('ix_sleep_id'))

    op.drop_table('sleep')
    with op.batch_alter_table('resting_heart_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resting_heart_rate_measurement_date'))
        batch_op.drop_index(batch_op.f('ix_resting_heart_rate_id'))

    op.drop_table('resting_heart_rate')
    with op.batch_alter_table('monthly_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_summaries_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_summaries_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_summaries_id'))

    op.drop_table('monthly_summaries')
    with op.batch_alter_table('lactate_threshold_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lactate_threshold_history_observed_at'))
        batch_op.drop_index(batch_op.f('ix_lactate_threshold_history_id'))
        batch_op.drop_index('idx_lactate_threshold_history_source_observed_at')
        batch_op.drop_index('idx_lactate_threshold_history_observed_at')

    op.drop_table('lactate_threshold_history')
    with op.batch_alter_table('hrv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hrv_measurement_date'))
        batch_op.drop_index(batch_op.f('ix_hrv_id'))

    op.drop_table('hrv')
    with op.batch_alter_table('health_data_missing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_data_missing_missing_date'))
        batch_op.drop_index(batch_op.f('ix_health_data_missing_id'))
        batch_op.drop_index(batch_op.f('ix_health_data_missing_data_type'))

    op.drop_table('health_data_missing')
    with op.batch_alter_table('garmin_performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garmin_performance_metrics_date'))

    op.drop_table('garmin_performance_metrics')
    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_summaries_id'))
        batch_op.drop_index(batch_op.f('ix_daily_summaries_date'))

    op.drop_table('daily_summaries')
    with op.batch_alter_table('body_battery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_battery_id'))
        batch_op.drop_index(batch_op.f('ix_body_battery_date'))

    op.drop_table('body_battery')
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_metric_key'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_id'))

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_types_type_key'))
        batch_op.drop_index(batch_op.f('ix_activity_types_id'))

    op.drop_table('activity_types')
    # ### end Alembic commands ###
