"""add_metric_provenance

Revision ID: 420b721e1bf8
Revises: a0aa219a0c49
Create Date: 2026-07-26 11:10:21.506153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420b721e1bf8'
down_revision: Union[str, Sequence[str], None] = 'a0aa219a0c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_provenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'metric_key', name='uq_metric_provenance_entity_metric')
    )
    with op.batch_alter_table('metric_provenance', schema=None) as batch_op:
        batch_op.create_index('idx_metric_provenance_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_metric_provenance_metric_key', ['metric_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_provenance_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_provenance_id'))
        batch_op.drop_index('idx_metric_provenance_metric_key')
        batch_op.drop_index('idx_metric_provenance_entity')

    op.drop_table('metric_provenance')
    # ### end Alembic commands ###
