"""add_sync_runs_and_sync_locks

Revision ID: a0aa219a0c49
Revises: 2e6ad7447506
Create Date: 2026-07-26 10:59:29.201403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aa219a0c49'
down_revision: Union[str, Sequence[str], None] = '2e6ad7447506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_locks',
    sa.Column('lock_name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lock_name')
    )
    with op.batch_alter_table('sync_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_locks_expires'), ['expires'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_locks_owner'), ['owner'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_status'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_job_type'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('sync_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_locks_owner'))
        batch_op.drop_index(batch_op.f('ix_sync_locks_expires'))

    op.drop_table('sync_locks')
    # ### end Alembic commands ###
